<?
/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional information regarding copyright ownership. Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the specific language governing permissions and limitations under the License.
 */

/**
 * @var Auth $auth
 */
$auths = $this->auths;
?>
<div class="container">
    <div class="hero-unit">
        <h1>Auths</h1>
        <p>Choose an Auth from the list below to edit</p>
    </div>
    <? if(!empty($this->messages)): ?>
    <div class="control-group success">
            <span class="help-block">
                <? foreach ($this->messages as $message): ?>
                <?=$message?>
                <? endforeach ?>
            </span>
    </div>
    <? endif ?>
    <div class="well">
        <div id="list">
            <div class="listItem">
                <div class="item-div pull-left"><span class="item1"><strong>Auth ID</strong></span></div>
                <div class="item-div pull-left"><span class="item2"><strong>Type</strong></span></div>
                <div class="item-div pull-left"><span class="item3"><strong>Details</strong></span></div>
                <div class="item-div pull-left" align="center"><span class="item4"><a href="/auth/create" class="btn btn-success">+</a></div>
            </div>
            <? foreach($auths as $auth){?>
            <div class="listItem">
                <div class="item-div pull-left"><label class="item1"><a href="/auth/<?=$auth->id;?>"><strong><?if(strlen($auth->id) > 15){ echo substr($auth->id, 0, 15) . "...";}else{ echo $auth->id;} ;?></strong></a></label></div>
                <div class="item-div pull-left"><span class="item2"><?=$auth->type;?></span></div>
                <div class="item-div pull-left"><span class="item3"><?
                    switch($auth->type){
                        case AuthType::$BASIC:
                            echo $auth->basicAuth->username;
                            break;
                        case AuthType::$WSSE:
                            print $auth->wsseAuth->username;
                            break;
                        case AuthType::$AUTHKEY:
                            print $auth->authKeyAuth->keyValue;
                            break;
                        case AuthType::$IPWHITELIST:
                            echo $auth->ipWhiteListAuth->ips[0]."...";
                            break;
                    }?></span></div>
                <div class="item-div pull-left" align="center">
                      <span class="item4">
                      <a class="btn btn-danger delete" href="/auth/<?=$auth->id?>/delete" >Delete</a>
                      </span>
                </div>
            </div>
            <?}?>
        </div>
    </div>
</div> <!-- /container -->