<?
require_once APPLICATION_PATH . '/models/Cert.class.php';

$flow = $this->flow;
$validationErrors = $this->validationErrors; //@$flow->flowScope['validationErrors'];
$ca = empty($this->ca) ? new Cert() : $this->ca;
$id = $ca->getId();
if (!isset($this->isNew)) { $this->isNew = empty($id); }
$formAction = $this->isNew ? "/certificate/ca/create" : "/certificate/ca/".$id;
?>
<?$t = new Zend_Translate(
    'gettext',  //the adapter
    APPLICATION_PATH.'/lang', //where the lang files will be stored
    'auto',  //set to auto include .mo files
    array('scan' => Zend_Translate::LOCALE_FILENAME) //set to scan lang files
);?>
<div class="container">
    <h1><?php echo $this->isNew ? $t->_("Add") : $t->_("Edit"); ?> <? echo $t->_("Trusted Certificate Authority")?></h1>
<? if(!empty($validationErrors['default'])):?>
    <div class="control-group error">
        <span class="help-inline"><? echo $t->_("Server Error")?>: <?=$validationErrors['default']?></span>
    </div>
<? endif; ?>
    <form class="well form-horizontal" method="POST" enctype="multipart/form-data">
        <fieldset>
            <div class="control-group">
                <label class="control-label" for="ca_name"><? echo $t->_("Name")?></label>
                <div class="controls">
                    <input type="text" class="input-xlarge" id="ca_name" name="ca_name" value="<?php echo $ca->getDisplayName(); ?>"/>
                    <input type="hidden" class="input-xlarge" id="ca_id" name="ca_id" value="<?php echo $id ?>" />
                    <span class="help-inline"><?=@$validationErrors['ca_name']?></span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="ca_file"><? echo $t->_("Certificate")?></label>
                <div class="controls">
                    <input type="file" id="ca_file" name="ca_file" value="<? echo $t->_("Choose file")?>" <?php if (!$this->isNew) { echo 'disabled="disabled"'; } ?>/>
                    <span class="help-inline"><?=@$validationErrors['ca_file']?></span>
                </div>
            </div>
            <input type="hidden" name="_faction" value="submit" />
            <input type="submit" class="btn confirm-toggle btn-primary" value="<?php echo $this->isNew ? $t->_('Create') : $t->_('Save'); ?> <? echo $t->_("Certificate Authority")?>" />
        </fieldset>
    </form>
</div> <!-- /container -->
