/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 * Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 02:26:27 PM CET 
//


package com.alu.e3.prov.restapi.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * The model to create an API on E3. 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "api", propOrder = {
		"id",
		"displayName",
		"version",
		"validation",
		"type",
		"subscriptionStep",
		"notificationFormat",
		"endpoint",
		"https",
		"authentication",
		"tdrEnabled",
		"status",
		"ipWhiteList",
		"contexts",
		"tdrOnUse",
		"tdrOnLimitReached",
		"tdr",
		"properties",
		"headerTransEnabled",
		"headerTransformations",
		"allowedHttpMethods",
		"proxySettings"
})
public class Api {

	/**
	 * The id of the API that could be provided.
	 */
	protected String id;
	/**
	 * The API name used for the display
	 */
	protected String displayName;
	/**
	 * The API version
	 */
	protected String version;

	/**
	 * Validation types 
	 */
	protected Validation validation;

	/**
	 * The API Type: PassThrough or Composite
	 */
	@XmlElement(name="type", required = true)
	protected ApiType type;

	/**
	 * If present, defines the subscription step
	 * for this API.
	 * Subscription: generates X-SubscriberID header.
	 * Notification: extracts X-SubscriberID.
	 */
	@XmlElement(name="subscriptionStep", required=false)
	protected SubscriptionStep subscriptionStep;

	/**
	 * If present, defines the notification format for this API.
	 * HEADER: notifyUrl header is extracted.
	 * WS_ADDRESSIING: &lt;To&gt; tag element content is extracted. 
	 */
	@XmlElement(name="notificationFormat", required=false)
	protected NotificationFormat notificationFormat;

	/**
	 * The API endpoint URL
	 */
	@XmlElement(required = true)
	protected String endpoint;  

	/**
	 * Whether the API should be exposed over HTTPS
	 */
	@XmlElement(required = true)
	protected HTTPSType https;

	/**
	 * The supported authentication associated to an API. E3 will use only these types to authenticate the API calls. 
	 */
	@XmlElement(required = true)
	protected ProvisionAuthentication authentication;

	/**
	 * The type of TDR to emit when the API is called.
	 */
	protected TypeAttribute tdrOnUse;

	/**
	 * The type of TDR to emit when the limit on the API is reached.
	 */
	protected TypeAttribute tdrOnLimitReached;

	/**
	 * Flag to enable or disable at provisioning time the TDR generation.
	 * Default is true
	 */
	protected TdrEnabled tdrEnabled = new TdrEnabled();

	/**
	 * The API status: active, inactive, pending
	 */
	@XmlElement(required = true)
	protected Status status;

    /**
     * The IP white list for the API.
     */
    @XmlElement(required = true)
    protected IpWhiteList ipWhiteList;

    /**
	 * The contexts definition for the API.
	 * <p>Could be: production, sandbox, test
	 */
	@XmlElementWrapper(name="contexts", required = true)
	@XmlElement(name="context", required = true)
	protected List<ApiContext> contexts;

	/**
	 * properties data that will be used by header transforms and/or tdr outputs.
	 */
	@XmlElementWrapper(name="properties")
	@XmlElement(name="property")
	protected List<Key> properties;

	/**
	 * The header transformations for the API.
	 */
	@XmlElementWrapper(name="headerTransformations", required = false)
	@XmlElement(name="headerTransformation", required = false)
	protected List<HeaderTransformation> headerTransformations;

	@XmlElement(name="headerTransEnabled", required=false)
	protected Boolean headerTransEnabled = true;

	/**
	 * The header transformations for the API.
	 */
	@XmlElementWrapper(name="allowedHttpMethods", required = false)
	@XmlElement(name="httpMethod", required = false)
	protected List<HttpMethod> allowedHttpMethods;
	
    protected ApiProxySettings proxySettings;



	/**
	 * Tells if the api is internal or not.
	 */
	@XmlTransient
	private Boolean internal = false;

	/**
	 * TDR data for static or dynamic TDR data 
	 */
	protected TdrData tdr;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the displayName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * Sets the value of the displayName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setDisplayName(String value) {
		this.displayName = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link ApiType }
	 *     
	 */
	public ApiType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link ApiType }
	 *     
	 */
	public void setType(ApiType value) {
		this.type = value;
	}

	/**
	 * Gets the value of the subscription property.
	 * 
	 * @return value
	 *     allowed object is
	 *     {@link SubscriptionStep }
	 */
	public SubscriptionStep getSubscriptionStep() {
		return subscriptionStep;
	}

	/**
	 * Sets the value of the subscriptionStep property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link SubscriptionStep }
	 */
	public void setSubscriptionStep(SubscriptionStep subscriptionStep) {
		this.subscriptionStep = subscriptionStep;
	}


	/**
	 * Gets the value of the notificationFormat property.
	 * 
	 * @return value
	 *     allowed object is
	 *     {@link NotificationFormat }
	 */
	public NotificationFormat getNotificationFormat() {
		return notificationFormat;
	}


	/**
	 * Sets the value of the notificationFormat property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link NotificationFormat }
	 */
	public void setNotificationFormat(NotificationFormat notificationFormat) {
		this.notificationFormat = notificationFormat;
	}

	/**
	 * Gets the value of the endpoint property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getEndpoint() {
		return endpoint;
	}

	/**
	 * Sets the value of the endpoint property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setEndpoint(String value) {
		this.endpoint = value;
	}


	/**
	 * Gets the value of the authentication property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link ProvisionAuthentication }
	 *     
	 */
	public ProvisionAuthentication getAuthentication() {
		return authentication;
	}

	/**
	 * Sets the value of the authentication property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link ProvisionAuthentication }
	 *     
	 */
	public void setAuthentication(ProvisionAuthentication value) {
		this.authentication = value;
	}

	/**
	 * Gets the value of the tdrOnUse property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getTdrOnUse() {
		if (tdrOnUse == null)
			return "";
		return tdrOnUse.getType();
	}

	/**
	 * Sets the value of the tdrOnUse property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setTdrOnUse(String value) {
		if (tdrOnUse == null)
			tdrOnUse = new TypeAttribute();
		tdrOnUse.setType(value);
	}

	/**
	 * Gets the value of the tdrOnLimitReached property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getTdrOnLimitReached() {
		if (tdrOnLimitReached == null)
			return "";
		return tdrOnLimitReached.getType();
	}

	/**
	 * Sets the value of the tdrOnLimitReached property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setTdrOnLimitReached(String value) {
		if (tdrOnLimitReached == null)
			tdrOnLimitReached = new TypeAttribute();
		tdrOnLimitReached.setType(value);
	}

	/**
	 * Gets the value of the tdrEnabled property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link TdrEnabled }
	 *     
	 */
	public TdrEnabled getTdrEnabled() {
		return tdrEnabled;
	}

	/**
	 * Sets the value of the tdrEnabled property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link TdrEnabled }
	 *     
	 */
	public void setTdrEnabled(TdrEnabled value) {
		this.tdrEnabled = value;
	}

	/**
	 * Gets the value of the status property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Status }
	 *     
	 */
	public Status getStatus() {
		return status;
	}

	/**
	 * Sets the value of the status property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Status }
	 *     
	 */
	public void setStatus(Status value) {
		this.status = value;
	}

    /**
     * Gets the value of the ipWhiteList property.
     * 
     * @return
     *     possible object is
     *     {@link IpWhiteList }
     *     
     */
    public IpWhiteList getIpWhiteList() {
        return ipWhiteList;
    }

    /**
     * Sets the value of the ipWhiteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpWhiteList }
     *     
     */
    public void setIpWhiteList(IpWhiteList value) {
        this.ipWhiteList = value;
    }    

    /**
	 * Gets the value of the contexts property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link ApiContext }
	 *     
	 */
	public List<ApiContext> getContexts() {
		if (contexts == null) {
			contexts = new ArrayList<ApiContext>();
		}
		return contexts;
	}

	/**
	 * Sets the value of the contexts property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link ApiContext }
	 *     
	 */
	public void setContexts(List<ApiContext> value) {
		this.contexts = value;
	}

	public TdrData getTdr() {
		return tdr;
	}

	public void setTdr(TdrData tdr) {
		this.tdr = tdr;
	}
	public HTTPSType getHttps() {
		return https;
	}

	public void setHttps(HTTPSType https) {
		this.https = https;
	}	 

	public Validation getValidation() {
		return validation;
	}

	public void setValidation(Validation validation) {
		this.validation = validation;
	}

	public List<Key> getProperties(){
		if(this.properties == null)
			this.properties = new ArrayList<Key>();
		return this.properties;
	}

	public void setProperties(List<Key> value){
		this.properties = value;
	}

	public List<HeaderTransformation> getHeaderTransformations(){
		if(this.headerTransformations == null)
			this.headerTransformations = new ArrayList<HeaderTransformation>();
		return this.headerTransformations;
	}

	public void setHeaderTransformations(List<HeaderTransformation> value){
		this.headerTransformations = value;
	}

	public Boolean getHeaderTransEnabled() {
		return headerTransEnabled;
	}

	public void setHeaderTransEnabled(boolean headerTransEnabled) {
		this.headerTransEnabled = headerTransEnabled;
	}

	public List<HttpMethod> getAllowedHttpMethods(){
		if(this.allowedHttpMethods == null)
			this.allowedHttpMethods = new ArrayList<HttpMethod>();
		return this.allowedHttpMethods;
	}

	public void setAllowedHttpMethods(List<HttpMethod> value){
		this.allowedHttpMethods = value;
	}

	public String getAllowedHttpMethodsAsString() {
		final String comma = ",";
		StringBuilder httpMethods = null;
		for(com.alu.e3.prov.restapi.model.HttpMethod m : this.getAllowedHttpMethods()) {
			if (httpMethods == null) {
				httpMethods = new StringBuilder (m.toString());
			} else {
				httpMethods.append(comma).append(m.toString());
			}
		}
			return httpMethods == null ? null : httpMethods.toString();
	}

	public void setAllowedHttpMethodsAsString(String in) {
		List<HttpMethod> methods = new ArrayList<HttpMethod>();
		if(in!=null)
			for(String m : in.split(","))
				methods.add(HttpMethod.valueOf(m));
		this.allowedHttpMethods = methods;
	}

	public Boolean getInternal(){
		return this.internal;
	}

	public void setInternal(boolean internal){
		this.internal = internal;
	}

	public ApiProxySettings getProxySettings() {
		return proxySettings;
	}

	public void setProxySettings(ApiProxySettings proxySettings) {
		this.proxySettings = proxySettings;
	}
}
