/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 * Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.30 at 11:23:09 AM CEST 
//


package com.alu.e3.prov.restapi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.alu.e3.prov.restapi.model.AuthIdsNoIdType;


/**
 * A bulk structure to associate a bucket of auths to several policies 
 */
@XmlRootElement(name="bulk")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bulkQuotaRLBucketType", propOrder = {

})
public class BulkPolicyQuotaRLBucketType {

    @XmlElement(required = true)
    protected PolicyIdsType policies;
    @XmlElement
    protected AuthIdsNoIdType quotaRLBucket;    
    
    /**
     * Gets the value of the policies property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyIdsType }
     *     
     */
    public PolicyIdsType getPolicies() {
        return policies;
    }

    /**
     * Sets the value of the policies property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyIdsType }
     *     
     */
    public void setPolicies(PolicyIdsType value) {
        this.policies = value;
    }

    /**
     * Gets the value of the quotaRLBucket property.
     * 
     * @return
     *     possible object is
     *     {@link AuthIdsNoIdType }
     *     
     */
    public AuthIdsNoIdType getQuotaRLBucket() {
        return quotaRLBucket;
    }

    /**
     * Sets the value of the quotaRLBucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthIdsNoIdType }
     *     
     */
    public void setQuotaRLBucket(AuthIdsNoIdType value) {
        this.quotaRLBucket = value;
    }	

}
