/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 * Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 02:26:27 PM CET 
//

package com.alu.e3.prov.restapi.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;

/**
 * Types of supported North Bound authentications when provisioning an API. 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "provisionAuthentication", propOrder = { "auths", "authKey" })
public class ProvisionAuthentication {

	/**
	 * List of supported auth types: basic, ipWhiteList, authKey 
	 */
	@XmlElementWrapper(name = "supportedTypes")
	@XmlElement(name = "type", required = true)
	protected List<AuthType> auths;

	/**
	 * When authKey is selected this info should be put to provide the authkey key name related to the created API
	 */
	protected Authkey authKey;

	/**
	 * Gets the value of the auths property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the auths property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAuths().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link AuthType }
	 * 
	 * 
	 */
	public List<AuthType> getAuths() {
		if (auths == null) {
			auths = new ArrayList<AuthType>();
		}
		return this.auths;
	}

	/**
	 * Gets the value of the authKey property.
	 * 
	 * @return possible object is {@link Authkey }
	 * 
	 */
	public Authkey getAuthKey() {
		return authKey;
	}

	/**
	 * Sets the value of the authKey property.
	 * 
	 * @param value
	 *            allowed object is {@link Authkey }
	 * 
	 */
	public void setAuthKey(Authkey value) {
		this.authKey = value;
	}

	public boolean getUseBasicAuth() {
		return getAuths().contains(AuthType.BASIC);
	}	

	public boolean getUseAuthKey() {
		return getAuths().contains(AuthType.AUTHKEY);
	}	

	public boolean getUseNoAuth() {
		return getAuths().contains(AuthType.NO_AUTH);
	}	

	public boolean getUseIpWhiteListAuth() {
		return getAuths().contains(AuthType.IP_WHITE_LIST);
	}

	public boolean getUseOAuth() {
		return getAuths().contains(AuthType.OAUTH);
	}	
	public boolean getUseWsse() {
		return getAuths().contains(AuthType.WSSE);
	}	


}
