<?
/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional information regarding copyright ownership. Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the specific language governing permissions and limitations under the License.
 */

$users = $this->users;
?>
<div class="container">
    <div class="hero-unit">
        <h1><? echo $this->translate("List of Users")?></h1>
        <p><? echo $this->translate("Choose a user from the list below to edit")?></p>
    </div>
    <div class="well">
        <div id="list">
            <div class="listItem">
                <div class="item-div pull-left"><span class="item1"><strong><? echo $this->translate("Username")?></strong></span></div>
                <div class="item-div pull-left"><span class="item2"><strong><? echo $this->translate("Real Name")?></strong></span></div>
                <div class="item-div pull-left"><span class="item2"><a href="/user/create" class="btn btn-success">+</a></div>
            </div>
            <? foreach($users as $user){?>
            <div class="listItem">
                <div class="item-div pull-left"><label class="item1"><a href="/user/<?=$user['id'];?>"><strong><?=@$user['username'];?></strong></a></label></div>
                <div class="item-div pull-left"><span class="item2"><?=@$user['real_name'];?></span></div>
                <div class="item-div pull-left">
                      <span class="item4">
                      <a href="/user/<?=$user['id']?>/delete" class="btn btn-danger"><? echo $this->translate("Delete")?></a>
                      </span>
                </div>
            </div>
            <?}?>
        </div>
    </div>
</div> <!-- /container -->
