<?/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional information regarding copyright ownership. Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the specific language governing permissions and limitations under the License.
 */
$ve = $this->validationErrors;
?>
<?$t = new Zend_Translate(
    'gettext',  //the adapter
    APPLICATION_PATH.'/lang', //where the lang files will be stored
    'auto',  //set to auto include .mo files
    array('scan' => Zend_Translate::LOCALE_FILENAME) //set to scan lang files
);?>
<div class="container">
    <h1><? echo $t->_("Login")?></h1>
    <? if(!empty($this->messages)): ?>
    <div class="control-group error">
            <span class="help-block">
                <? foreach ($this->messages as $message): ?>
                <?=$message?>
                <? endforeach ?>
            </span>
    </div>
    <? endif ?>
    <form method="POST" class="well form-horizontal">
        <fieldset>
            <div class="control-group <?=!empty($ve['login']['username'])?"error":""?>" >
                <label class="control-label" for="username"><? echo $t->_("Username")?></label>
                <div class="controls">
                    <input type="text" name="username" id="username" value="<?=$this->username?>"/>
                    <span class="help-inline"><?=@$ve['login']['username']?></span>
                </div>
            </div>
            <div class="control-group <?=!empty($ve['login']['password'])?"error":""?>">
                <label class="control-label" for="password"><? echo $t->_("Password")?></label>
                <div class="controls">
                    <input type="password" name="password" id="password"/>
                    <span class="help-inline"><?=@$ve['login']['password']?></span>
                </div>
            </div>
            <input type="submit" class="btn btn-inverse" value="<? echo $t->_("Login")?>"/>
        </fieldset>
    </form>
</div>