/**
 * Copyright © 2012 Alcatel-Lucent.
 *
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 * Licensed to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 02:26:36 PM CET 
//


package com.alu.e3.auth.model;

/**
 * Enum for supported North Bound authentication types : basic, authKey, IP White List  
 */
public enum AuthType {

	BASIC("basic"),
	AUTHKEY("authKey"),
	IP_WHITE_LIST("ipWhiteList"),
	NO_AUTH("noAuth"),
	// TODO: remove from open source version
	O_AUTH("oAuth"),
	WSSE("wsse");

	private final String value;

	AuthType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static AuthType fromValue(String v) {
		for (AuthType c: AuthType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
